#fastdfs设置
fdfs:
  so-timeout: 2500       # 读取时间
  connect-timeout: 5000   # 连接超时时间
  thumb-image:           # 缩略图
    width: 100
    height: 100
  tracker-list:          # tracker服务配置地址列表
    - www.0622cc.cn:22122
upload:
  base-url: www.0622cc.cn/
  allow-types:
    - image/jpeg
    - image/png
    - image/bmp
spring:
  servlet:
    multipart:
      max-file-size: 5MB

#logging.level.root: info